### ISSUE TITLE
バージョン番号はコミットメッセージにより決定される

### ISSUE THREAD

**Issue by azu** [azu/azu#16]
[webpro/release-it](https://github.com/webpro/release-it "webpro/release-it") とか [azu/release-changelog](https://github.com/azu/release-changelog "azu/release-changelog") とかで、
ニンゲンがバージョン番号を打つ必要性が大分薄くなってきた気がする。

上記のツールインタラクティブだけど、"npm publishするかどうか"しかいつも選ばないので、
バージョン番号の決定はニンゲンがやる必要はあんまりない気がしてる。
semver(patch,minor,major)をニンゲンが指定する意味が薄いという事で、気分で2.0.0みたいなキリがいいバージョンにすることはありだと思う

### major

コミットメッセージにBREAKING CHANGEが出現したらあげる

### minor

`feat` がでたらあげる

### patch

その他

というコミットメッセージから、自動的にバージョン番号をふって付けるツールとかどうだろ?

**Comment by azu** [comment]
実現してた！
[boennemann/semantic-release](https://github.com/boennemann/semantic-release "boennemann/semantic-release")

**Comment by teppeis** [comment]
semantic-release、例の https://github.com/maxogden/maintenance-modules に書いてあったので見つけました。
travisに設定してpushごとに自動リリースすべし！っていうかなりストロングスタイルですね。
6to5向きかもｗ

**Comment by azu** [comment]
[stevemao/conventional-recommended-bump](https://github.com/stevemao/conventional-recommended-bump "stevemao/conventional-recommended-bump") まさに思ってたのをそのまま作ってた人がいた
