### ISSUE TITLE
色々なプラグイン機構のパターン

### ISSUE THREAD

**Issue by azu** [azu/azu#60]
[OSS開発の活発さの維持と良いソフトウェア設計の間には緊張関係があるのだろうか? - t-wadaのブログ](http://t-wada.hatenablog.jp/entry/active-oss-development-vs-simplicity "OSS開発の活発さの維持と良いソフトウェア設計の間には緊張関係があるのだろうか? - t-wadaのブログ")

> プラグイン機構を作ること拡張機能をプラガブルにすることで、開発に参加する間口を広げる

を見てて、色々なプラグイン機構の作り方の仕組みのまとめがあるといいのではと思った。

例えば、[ESLint](http://eslint.org/ "ESLint")みたいな、Nodeのtype毎にemitしてプラグイン側でNode毎の処理を書いていく事でtraverse処理をプラグイン内部で持たないようにするパターンとか、
[mdast/plugins.md at master · wooorm/mdast](https://github.com/wooorm/mdast/blob/master/doc/plugins.md "mdast/plugins.md at master · wooorm/mdast")みたいに`use`を使ったNodeでよく見るパターンとか、
[gulp](https://github.com/gulpjs/gulp "gulp")みたいなstreamを使ったパターンとか色々なものがあったりする。

それぞれの方式が何に向いてるのかとかデザインパターン的に知れるものがあると便利そう

**Comment by twada** [comment]
これは絶対に価値のあるまとめになると思います。 @azu++

**Comment by azu** [comment]
https://github.com/azu/JavaScript-Plugin-Architecture で進めてる。
#42 の方についての検証目的半分。

**Comment by azu** [comment]
書いた [JavaScript Plugin Architectureというプラグイン設計について学ぶ無料の電子書籍を書いた | Web Scratch](http://efcl.info/2016/06/06/JavaScript-Plugin-Architecture/ "JavaScript Plugin Architectureというプラグイン設計について学ぶ無料の電子書籍を書いた | Web Scratch")
