### ISSUE TITLE
JavaScript、Node.js 教材のレビューの仕事を azu 様に依頼したいのですが、どちらで連絡を取れば良いでしょうか？

### ISSUE THREAD

**Issue by DDRAGON** [azu/azu#88]
azu さんお疲れ様です。
企業にて、日本語のプログラミング教材の作成を行っております、D_drAAgon と申します。

この度は、JavaScript、Node.js 教材のレビューの仕事を azu 様に依頼したいと考えているのでが、仕事の依頼の相談などはどちらで連絡を取れば良いでしょうか？
ご教授いただければと思っております🙇‍♂️

何卒、よろしくお願いいたします。

**Comment by sifue** [comment]
ドワンゴ/学校法人角川ドワンゴ学園の吉村です。本件どうぞよろしくお願い致します。

**Comment by azu** [comment]
こんにちは。
すでに作成済みのコンテンツに対して1度全体的にレビューするようなイメージでしょうか?
それとも、作成中のコンテンツに対して継続的なレビュー(期間的な契約をして、その期間中に作成されたコンテンツのレビュー)をするイメージでしょうか?

前者のような(いわゆる[技術書のレビュー](https://note.golden-lucky.net/2018/03/blog-post.html)や査読に近いイメージ)ものであれば、ベストエフォートで対応できると思います。

後者のような、ある程度拘束時間/期間が発生するようなものであれば、モチベーションとの兼ね合いがあるため要相談になるかと思います。

メールアドレスは `azuciao@gmail.com` になります。

**Comment by azu** [comment]
メールのほうでやり取りためIssueはクローズします。
