### ISSUE TITLE
Broken voting-badge repo

### ISSUE THREAD

**Issue by LucBerge** [azu/azu#90]
Hi,
Your voting badge app is not working anymore, Heroku free version has changed.
I found a way to fix it with [Cyclic](https://www.cyclic.sh/) but it requires deep changes.
Could you please transfert the ownership as you said [here](https://github.com/azu/voting-badge/issues/4#issuecomment-771621381) ?

I'm using shield.io endpoint to make it fully compatible.

Thank you

**Comment by azu** [comment]
I've retired my Heroku account and I can not transfer the heroku app.
Latest source is https://github.com/azu/voting-badge 
You can fork it from https://github.com/azu/voting-badge/fork.

Thanks for work.

**Comment by LucBerge** [comment]
If I fork your repo, it will lost the stars, the views and it will have less visibility. I don't need you to transfer the Heroku app, I'll host it on Cyclic.Le 9 nov. 2022 11:56 PM, azu ***@***.***> a écrit :
I've retired my Heroku account and I can not transfer the heroku app.
Latest source is https://github.com/azu/voting-badge
You can fork it from https://github.com/azu/voting-badge/fork.
Thanks for work.

**Comment by LucBerge** [comment]
If I fork your repo, it will lost the stars, the views and it will have less visibility. I don't need you to transfer the Heroku app, I'll host it on Cyclic.
